### ISSUE TITLE
not localized messages are sent if they are not responses to user

### ISSUE THREAD

**Issue by tarmo888** [byteball/username-attestation#3]
These are not sending out translated messages because these events don't call `i18n.setLocale()` function with the language that user has selected.
https://github.com/byteball/username-attestation/blob/b4dad8f40bbb402b156f3aeb26727c8d0f38a5d5/attestation.js#L214
https://github.com/byteball/username-attestation/blob/b4dad8f40bbb402b156f3aeb26727c8d0f38a5d5/attestation.js#L368
https://github.com/byteball/username-attestation/blob/b4dad8f40bbb402b156f3aeb26727c8d0f38a5d5/modules/username-attestation.js#L64

There are probably more bot responses that are not responses to user message and they send default English messages instead.

**Comment by tonyofbyteball** [comment]
Thanks, fixed in https://github.com/byteball/username-attestation/commit/34bd5d8a9147b1c33a521cd96f26de095aeed395
